### ISSUE TITLE
intro

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/ph-react-static#1]
Executive person: Prem Dutta
Contact: https://angel.co/groceristar/recruiting/messages/2060288

prev code located here: https://github.com/atherdon/ph-st 
compiled HTML are here: https://github.com/atherdon/ph-st/tree/master/build

checklist
as it's a big task, please tell me your step by step plan. 
it'll be cool to go from basic stuff first, like: 

- implement header and footer and container -->
- then go to each block -->
- and show me the progress each time when you finish the item

So i can review it, and make some corretions.

in order to be able see the result online - we must to push repository code on https://www.netlify.com/
when you create an account here and try to move this repo - you'll need to get a grant access from me.
Do it - i'll receive a notification and i'll approve it.

**Comment by atherdon** [comment]
Not sure about your React skills, so let's use Create React App starter. But later, i want to use gatsby, because we use it on our other frontend related projects too

**Comment by PremDutta** [comment]
shall I start learning react ?
because i know bit of it.

**Comment by PremDutta** [comment]
bt still i have to learn a lot.

**Comment by atherdon** [comment]
@PremDutta i think yes

**Comment by atherdon** [comment]
@PremDutta do you need any help or maybe you can show some progress to me?
